services:
  - name: n8n-render
    type: web
    runtime: image
    repo: https://github.com/bevanamit/n8n-render.git
    image:
      url: docker.io/n8nio/n8n:latest
    region: oregon
    plan: free
    autoDeploy: true

    envVars:
      - key: N8N_PUBLIC_URL
        value: "https://n8n-render-4p4f.onrender.com/"

      - key: N8N_PROTOCOL
        value: "https"

      - key: N8N_HOST
        value: "n8n-render-4p4f.onrender.com"

      - key: N8N_PORT
        value: "443"

      - key: WEBHOOK_URL
        value: "https://n8n-render-4p4f.onrender.com/"

      - key: N8N_EDITOR_BASE_URL
        value: "https://n8n-render-4p4f.onrender.com/"

      - key: VUE_APP_URL_BASE_API
        value: "https://n8n-render-4p4f.onrender.com/"

      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"

      - key: N8N_BASIC_AUTH_USER
        value: "admin"

      - key: N8N_BASIC_AUTH_PASSWORD
        value: "strongpassword"

      - key: GENERIC_TIMEZONE
        value: "Asia/Kolkata"

      - key: N8N_ENCRYPTION_KEY
        generateValue: true

    disk:
      name: n8n-data
      mountPath: /home/node/.n8n
      sizeGB: 1
